### ISSUE TITLE
High-level tests quality metric

### ISSUE THREAD

**Issue by kolov** [SonarQubeCommunity/sonar-pitest#10]
The plugin creates an issue when a mutant survives. To use the plugin to evaluate the overall quality of the tests, instead of dealing with separate issues, some general metric would be useful, similar to Test Coverage. For example: 90% of the mutations do not survive. 
Are there any plans in this direction?

**Comment by thomas-mc-work** [comment]
Isn't this possible with quality gates?

Like that:

![screenshot - 27 05 2016 - 15 20 56](https://cloud.githubusercontent.com/assets/6542498/15609172/c1764526-241e-11e6-9302-594005e45f5c.png)

**Comment by kolov** [comment]
Thanks a lot, So the metric I suggested is already there. This is great, a pity that I couldn't figure that out by reading the documentation https://github.com/SonarQubeCommunity/sonar-pitest - no Mutations Coverage metric mentioned: 
> Right now the integration of these results is quite simple, "survived mutants" on code  covered by tests are seen as SonarQube issues
I think mentioning the Mutations Coverage  metric in the documentation wold be useful.
